title: skipifzero
description: "Blogging about programming, graphics and games."
baseurl: ""
url: "http://www.skipifzero.com"

email: petor@hstroem.se
github_username: PetorSFZ

# Build settings
markdown: kramdown

highlighter: rouge